### ISSUE TITLE
Address wrong in article

### ISSUE THREAD

**Issue by betgear** [hampussandberg/HexConnect#1]
Hi,

In your article you mention 0x60080000 - For commands, surely this should be 0x60020000.

This could be confusing for people coming across your information and trying to use it for their own display.

Cheers

Glen.

**Comment by betgear** [comment]
Sorry, should have left a link

https://github.com/hampussandberg/HexConnect/wiki/LCD-ER_TFTM070_5

**Comment by hampussandberg** [comment]
0x60080000 is correct for the command, see table
